version: '3'

services:
  trojan:
      image: trojangfw/trojan
      ports:
        - "443:443"
      command: ["/bin/sh", "/wait_for_caddy.sh", "trojan", "config.json"]
      volumes:
        - ./trojan/config:/config
        - ./ssl:/ssl
        - ./trojan/wait_for_caddy.sh:/wait_for_caddy.sh
      restart: always
      depends_on: 
        - caddy

  caddy:
      image: abiosoft/caddy
      ports:
        - "8080:8080"
        - "80:80"
      volumes:
        - ./wwwroot:/usr/src
        - ./caddy/Caddyfile:/etc/Caddyfile
        - ./ssl:/root/.caddy/acme/acme-v02.api.letsencrypt.org/sites
      restart: always
